# Generated by Django 4.2.3 on 2023-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_country',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
