# Generated by Django 4.2.3 on 2023-07-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0003_flight_created_at_flight_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
