# Generated by Django 4.2.3 on 2023-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0004_alter_event_event_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_country',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
