# Generated by Django 4.2.3 on 2023-07-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0005_alter_event_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='event_name',
            field=models.CharField(default='name', max_length=64),
            preserve_default=False,
        ),
    ]
