# Generated by Django 4.2.3 on 2023-07-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_events', '0006_flight_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flights_backhome',
            new_name='flights_arriving',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flights_going',
            new_name='flights_departing',
        ),
    ]
